#!/usr/bin/env python3

db_file = "stats.db"

create_player_stats = """
create table if not exists PlayerStats 
(
    log_id int,
    player_id int,
    tf2_class text,
    kills int,
    deaths int,
    assists int,
    team int,
    dmg int,
    dt int,
    total_time int, 
    med_drops int,
    heals_received int,
    heal int,
    drops int,
    ubers int,
    deaths_with_95_99_uber int,
    deaths_within_20s_after_uber int,
    advantages_lost int,
    biggest_advantage_lost int,
    avg_time_before_healing int,
    avg_time_to_build int,
    avg_time_before_using int,
    uber_length real,
    mid_deaths int,
    mids_survived int,
    backstabs int,
    headshots_hit int,
    soldier_kills int,
    sniper_kills int,
    medic_kills int,
    scout_kills int,
    spy_kills int,
    pyro_kills int,
    engineer_kills int,
    demoman_kills int,
    heavyweapons_kills int,
    soldier_assists int,
    sniper_assists int,
    medic_assists int,
    scout_assists int,
    spy_assists int,
    pyro_assists int,
    engineer_assists int,
    demoman_assists int,
    heavyweapons_assists int,
    soldier_deaths int,
    sniper_deaths int,
    medic_deaths int,
    scout_deaths int,
    spy_deaths int,
    pyro_deaths int,
    engineer_deaths int,
    demoman_deaths int,
    heavyweapons_deaths int,
    primary key (log_id, player_id, tf2_class )
);"""

insert_player_stats = """
insert into PlayerStats values
(
:log_id,
:player_id,
:tf2_class,
:kills,
:deaths,
:assists,
:team,
:dmg,
:dt,
:total_time,
:med_drops,
:heals_received,
:heal,
:drops,
:ubers,
:deaths_with_95_99_uber,
:deaths_within_20s_after_uber,
:advantages_lost,
:biggest_advantage_lost,
:avg_time_before_healing,
:avg_time_to_build,
:avg_time_before_using,
:uber_length,
:mid_deaths,
:mids_survived,
:headshots_hit,
:backstabs,
:soldier_kills,
:sniper_kills,
:medic_kills,
:scout_kills,
:spy_kills,
:pyro_kills,
:engineer_kills,
:demoman_kills,
:heavyweapons_kills,
:soldier_assists,
:sniper_assists,
:medic_assists,
:scout_assists,
:spy_assists,
:pyro_assists,
:engineer_assists,
:demoman_assists,
:heavyweapons_assists,
:soldier_deaths,
:sniper_deaths,
:medic_deaths,
:scout_deaths,
:spy_deaths,
:pyro_deaths,
:engineer_deaths,
:demoman_deaths,
:heavyweapons_deaths
);
"""


